# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voyage', '0002_auto_20151210_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFaq',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('question', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['question'],
                'db_table': 'contribute_adminfaq',
                'verbose_name': 'Frequently Asked Question For Admins',
                'verbose_name_plural': 'Frequently Asked Question For Admins',
            },
        ),
        migrations.CreateModel(
            name='DeleteVoyageContribution',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('notes',
                 models.TextField(help_text=b'Notes for the contribution',
                                  max_length=10000,
                                  verbose_name=b'Notes')),
                ('status',
                 models.IntegerField(
                     help_text=b'Indicates whether the contribution is still '
                     b'being edited, committed, discarded etc',
                     verbose_name=b'Status')),
                ('deleted_voyages_ids',
                 models.CommaSeparatedIntegerField(
                     help_text=b'The voyage_id of each Voyage being deleted '
                     b'by this contribution',
                     max_length=255,
                     verbose_name=b'Deleted voyage ids')),
                ('contributor',
                 models.ForeignKey(related_name='+',
                                   to=settings.AUTH_USER_MODEL,
                                   on_delete=models.CASCADE)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditVoyageContribution',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('notes',
                 models.TextField(help_text=b'Notes for the contribution',
                                  max_length=10000,
                                  verbose_name=b'Notes')),
                ('status',
                 models.IntegerField(
                     help_text=b'Indicates whether the contribution is still '
                     b'being edited, committed, discarded etc',
                     verbose_name=b'Status')),
                ('edited_voyage_id',
                 models.IntegerField(
                     help_text=b'The voyage_id of the Voyage edited by this '
                     b'bcontribution',
                     verbose_name=b'Edited voyage id')),
                ('contributor',
                 models.ForeignKey(related_name='+',
                                   to=settings.AUTH_USER_MODEL,
                                   on_delete=models.CASCADE)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterimArticleSource',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('authors',
                 models.TextField(max_length=1000, null=True, blank=True)),
                ('article_title',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('journal',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('volume_number',
                 models.CharField(max_length=20, null=True, blank=True)),
                ('year', models.IntegerField(null=True)),
                ('page_start', models.IntegerField(null=True)),
                ('page_end', models.IntegerField(null=True)),
                ('information',
                 models.TextField(max_length=1000, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterimBookSource',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('authors',
                 models.TextField(max_length=1000, null=True, blank=True)),
                ('book_title',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('publisher',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('place_of_publication',
                 models.CharField(max_length=20, null=True, blank=True)),
                ('year', models.IntegerField(null=True)),
                ('page_start', models.IntegerField(null=True)),
                ('page_end', models.IntegerField(null=True)),
                ('information',
                 models.TextField(max_length=1000, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterimOtherSource',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('title', models.CharField(max_length=255,
                                           null=True,
                                           blank=True)),
                ('location',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('page', models.CharField(max_length=20, null=True,
                                          blank=True)),
                ('information',
                 models.TextField(max_length=1000, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterimPrimarySource',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('name_of_library_or_archive',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('location_of_library_or_archive',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('series_or_collection',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('volume_or_box_or_bundle',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('document_detail',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('information',
                 models.TextField(max_length=1000, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterimSlaveNumber',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('var_name',
                 models.CharField(
                     max_length=20,
                     verbose_name=b'Slave number code-book variable name')),
                ('number', models.IntegerField(verbose_name=b'Number')),
            ],
        ),
        migrations.CreateModel(
            name='InterimVoyage',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('name_of_vessel',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('year_ship_constructed',
                 models.IntegerField(null=True, blank=True)),
                ('year_ship_registered',
                 models.IntegerField(null=True, blank=True)),
                ('tonnage_of_vessel', models.IntegerField(null=True,
                                                          blank=True)),
                ('guns_mounted', models.IntegerField(null=True, blank=True)),
                ('first_ship_owner',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('second_ship_owner',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('additional_ship_owners',
                 models.TextField(max_length=1000, null=True, blank=True)),
                ('number_of_ports_called_prior_to_slave_purchase',
                 models.IntegerField(null=True, blank=True)),
                ('number_of_new_world_ports_called_prior_to_disembarkation',
                 models.IntegerField(null=True, blank=True)),
                ('date_departure',
                 models.CommaSeparatedIntegerField(max_length=10,
                                                   null=True,
                                                   blank=True)),
                ('date_slave_purchase_began',
                 models.CommaSeparatedIntegerField(max_length=10,
                                                   null=True,
                                                   blank=True)),
                ('date_vessel_left_last_slaving_port',
                 models.CommaSeparatedIntegerField(max_length=10,
                                                   null=True,
                                                   blank=True)),
                ('date_first_slave_disembarkation',
                 models.CommaSeparatedIntegerField(max_length=10,
                                                   null=True,
                                                   blank=True)),
                ('date_second_slave_disembarkation',
                 models.CommaSeparatedIntegerField(max_length=10,
                                                   null=True,
                                                   blank=True)),
                ('date_third_slave_disembarkation',
                 models.CommaSeparatedIntegerField(max_length=10,
                                                   null=True,
                                                   blank=True)),
                ('date_return_departure',
                 models.CommaSeparatedIntegerField(max_length=10,
                                                   null=True,
                                                   blank=True)),
                ('date_voyage_completed',
                 models.CommaSeparatedIntegerField(max_length=10,
                                                   null=True,
                                                   blank=True)),
                ('length_of_middle_passage',
                 models.IntegerField(null=True, blank=True)),
                ('first_captain',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('second_captain',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('third_captain',
                 models.CharField(max_length=255, null=True, blank=True)),
                ('notes',
                 models.TextField(help_text=b'Notes for the interim voyage',
                                  max_length=10000,
                                  null=True,
                                  verbose_name=b'Notes',
                                  blank=True)),
                ('african_resistance',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Resistance',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('first_place_of_landing',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('first_place_of_slave_purchase',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('first_port_intended_disembarkation',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('first_port_intended_embarkation',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('national_carrier',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Nationality',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('place_of_call_before_atlantic_crossing',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('port_of_departure',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('port_voyage_ended',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('principal_place_of_slave_disembarkation',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('principal_place_of_slave_purchase',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('rig_of_vessel',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.RigOfVessel',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('second_place_of_landing',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('second_place_of_slave_purchase',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('second_port_intended_disembarkation',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('second_port_intended_embarkation',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('ship_construction_place',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('ship_registration_place',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('third_place_of_landing',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('third_place_of_slave_purchase',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.Place',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('ton_type',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.TonType',
                                   null=True,
                                   on_delete=models.CASCADE)),
                ('voyage_outcome',
                 models.ForeignKey(related_name='+',
                                   blank=True,
                                   to='voyage.ParticularOutcome',
                                   null=True,
                                   on_delete=models.CASCADE)),
            ],
        ),
        migrations.CreateModel(
            name='MergeVoyagesContribution',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('notes',
                 models.TextField(help_text=b'Notes for the contribution',
                                  max_length=10000,
                                  verbose_name=b'Notes')),
                ('status',
                 models.IntegerField(
                     help_text=b'Indicates whether the contribution is still '
                     b'being edited, committed, discarded etc',
                     verbose_name=b'Status')),
                ('merged_voyages_ids',
                 models.CommaSeparatedIntegerField(
                     help_text=b'The voyage_id of each Voyage being merged by '
                     b'this contribution',
                     max_length=255,
                     verbose_name=b'Merged voyage ids')),
                ('contributor',
                 models.ForeignKey(related_name='+',
                                   to=settings.AUTH_USER_MODEL,
                                   on_delete=models.CASCADE)),
                ('interim_voyage',
                 models.ForeignKey(related_name='+',
                                   to='contribute.InterimVoyage',
                                   on_delete=models.CASCADE)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewVoyageContribution',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('notes',
                 models.TextField(help_text=b'Notes for the contribution',
                                  max_length=10000,
                                  verbose_name=b'Notes')),
                ('status',
                 models.IntegerField(
                     help_text=b'Indicates whether the contribution is still '
                     b'being edited, committed, discarded etc',
                     verbose_name=b'Status')),
                ('contributor',
                 models.ForeignKey(related_name='+',
                                   to=settings.AUTH_USER_MODEL,
                                   on_delete=models.CASCADE)),
                ('interim_voyage',
                 models.ForeignKey(related_name='+',
                                   to='contribute.InterimVoyage',
                                   on_delete=models.CASCADE)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id',
                 models.AutoField(verbose_name='ID',
                                  serialize=False,
                                  auto_created=True,
                                  primary_key=True)),
                ('institution', models.CharField(max_length=255)),
                ('new_material_and_sources',
                 models.TextField(max_length=1000)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL,
                                              on_delete=models.CASCADE)),
            ],
        ),
        migrations.AddField(
            model_name='interimslavenumber',
            name='interim_voyage',
            field=models.ForeignKey(related_name='slave_numbers',
                                    to='contribute.InterimVoyage',
                                    on_delete=models.CASCADE),
        ),
        migrations.AddField(
            model_name='interimprimarysource',
            name='interim_voyage',
            field=models.ForeignKey(related_name='primary_sources',
                                    to='contribute.InterimVoyage',
                                    on_delete=models.CASCADE),
        ),
        migrations.AddField(
            model_name='interimothersource',
            name='interim_voyage',
            field=models.ForeignKey(related_name='other_sources',
                                    to='contribute.InterimVoyage',
                                    on_delete=models.CASCADE),
        ),
        migrations.AddField(
            model_name='interimbooksource',
            name='interim_voyage',
            field=models.ForeignKey(related_name='book_sources',
                                    to='contribute.InterimVoyage',
                                    on_delete=models.CASCADE),
        ),
        migrations.AddField(
            model_name='interimarticlesource',
            name='interim_voyage',
            field=models.ForeignKey(related_name='article_sources',
                                    to='contribute.InterimVoyage',
                                    on_delete=models.CASCADE),
        ),
        migrations.AddField(
            model_name='editvoyagecontribution',
            name='interim_voyage',
            field=models.ForeignKey(related_name='+',
                                    to='contribute.InterimVoyage',
                                    on_delete=models.CASCADE),
        ),
    ]
