# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 14:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0002_auto_20160113_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterimPreExistingSource',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('voyage_ids',
                 models.CommaSeparatedIntegerField(max_length=255)),
                ('action', models.IntegerField(default=0)),
                ('original_ref', models.CharField(max_length=255)),
                ('full_ref', models.TextField(max_length=1000)),
                ('notes',
                 models.TextField(blank=True, max_length=1000, null=True)),
                ('interim_voyage',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='pre_existing_sources',
                                   to='contribute.InterimVoyage',
                                   on_delete=models.CASCADE)),
            ],
        ),
    ]
