# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribute', '0003_interimpreexistingsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField()),
                ('response', models.IntegerField()),
                ('editor_comments', models.TextField(verbose_name=b'Editor comments')),
                ('final_decision', models.IntegerField()),
                ('archived', models.BooleanField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('suggested_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVoyageContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text=b'Reviewer notes', max_length=10000, verbose_name=b'Notes')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribute.ReviewRequest')),
                ('review_interim_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contribute.InterimVoyage')),
            ],
        ),
        migrations.AddField(
            model_name='deletevoyagecontribution',
            name='review_request',
            field=models.ManyToManyField(to='contribute.ReviewRequest'),
        ),
        migrations.AddField(
            model_name='editvoyagecontribution',
            name='review_request',
            field=models.ManyToManyField(to='contribute.ReviewRequest'),
        ),
        migrations.AddField(
            model_name='mergevoyagescontribution',
            name='review_request',
            field=models.ManyToManyField(to='contribute.ReviewRequest'),
        ),
        migrations.AddField(
            model_name='newvoyagecontribution',
            name='review_request',
            field=models.ManyToManyField(to='contribute.ReviewRequest'),
        ),
    ]
