# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 19:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0015_interimpreexistingsource_original_short_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interimarticlesource',
            name='created_voyage_sources',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='voyage.VoyageSources'),
        ),
        migrations.AlterField(
            model_name='interimbooksource',
            name='created_voyage_sources',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='voyage.VoyageSources'),
        ),
        migrations.AlterField(
            model_name='interimnewspapersource',
            name='created_voyage_sources',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='voyage.VoyageSources'),
        ),
        migrations.AlterField(
            model_name='interimprimarysource',
            name='created_voyage_sources',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='voyage.VoyageSources'),
        ),
        migrations.AlterField(
            model_name='interimprivatenoteorcollectionsource',
            name='created_voyage_sources',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='voyage.VoyageSources'),
        ),
        migrations.AlterField(
            model_name='interimunpublishedsecondarysource',
            name='created_voyage_sources',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='voyage.VoyageSources'),
        ),
    ]
