# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 19:56
from __future__ import unicode_literals

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0019_auto_20170302_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletevoyagecontribution',
            name='deleted_voyages_ids',
            field=models.CharField(
                help_text=b'The voyage_id of each Voyage being deleted by '
                b'this contribution',
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Deleted voyage ids'),
        ),
        migrations.AlterField(
            model_name='interimpreexistingsource',
            name='original_short_ref',
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='interimpreexistingsource',
            name='voyage_ids',
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ]),
        ),
        migrations.AlterField(
            model_name='mergevoyagescontribution',
            name='merged_voyages_ids',
            field=models.CharField(
                help_text=b'The voyage_id of each Voyage being merged by this '
                b'contribution',
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Merged voyage ids'),
        ),
    ]
