# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0020_auto_20171231_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='is_intra_american',
            field=models.BooleanField(
                default=False,
                help_text=b'The resulting voyage is IntraAmerican'),
        ),
    ]
