# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-25 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0021_reviewrequest_is_intra_american'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrequest',
            name='is_intra_american',
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='dataset',
            field=models.IntegerField(
                default=0,
                help_text=b'Which dataset the voyage belongs to '
                b'(e.g. Transatlantic, IntraAmerican)'
            ),
        ),
    ]
