# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-21 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0022_auto_20200425_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='interimvoyage',
            name='african_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interimvoyage',
            name='cargo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interimvoyage',
            name='voyage_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
