# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-01-31 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0020_auto_20230131_1336'),
        ('contribute', '0023_auto_20220621_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='interimvoyage',
            name='fourth_port_intended_disembarkation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.Place'),
        ),
        migrations.AddField(
            model_name='interimvoyage',
            name='third_port_intended_disembarkation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.Place'),
        ),
    ]
