from __future__ import unicode_literals

from fabric.api import env, local, task

##
# automated build/test tasks
##


##
# deploy tasks
##

env.project = 'voyages'
env.rev_tag = ''
env.git_rev = ''
env.remote_path = '/home/httpd/sites/voyages'
env.url_prefix = None
env.remote_proxy = None
env.remote_acct = 'voyages'


@task
def clean():
    '''Remove build/dist artifacts generated by deploy task'''
    local('rm -rf build dist')
    # should we do any remote cleaning?
