from __future__ import unicode_literals

import os
import re
import shutil

from fabric.api import (abort, env, lcd, local, prefix, put, puts, require,
                        run, sudo, task)
from fabric.colors import green, yellow
from fabric.context_managers import cd, hide, settings
from fabric.contrib import files
from fabric.contrib.console import confirm

import voyages

##
# automated build/test tasks
##


##
# deploy tasks
##

env.project = 'voyages'
env.rev_tag = ''
env.git_rev = ''
env.remote_path = '/home/httpd/sites/voyages'
env.url_prefix = None
env.remote_proxy = None
env.remote_acct = 'voyages'


@task
def clean():
    '''Remove build/dist artifacts generated by deploy task'''
    local('rm -rf build dist')
    # should we do any remote cleaning?
