// form data //
// flag
var flagData = [
	{id:0, text:'Spain', value:"1"},
	{id:1, text:'Uruguay', value:"1"},
	{id:2, text:'Portugal', value:"1"},
	{id:3, text:'Brazil', value:"1"},
	{id:4, text:'Great Britain', value:"1"},
	{id:5, text:'Netherlands', value:"1"},
	{id:6, text:'U.S.A', value:"1"},
	{id:7, text:'France', value:"1"},
	{id:8, text:'Denmark', value:"1"},
	{id:9, text:'Hanse Towns, Brandenburg', value:"1"},
	{id:10, text:'Sweden', value:"1"},
	{id:11, text:'Norway', value:"1"},
	{id:12, text:'Argentina', value:"1"},
	{id:13, text:'Russia', value:"1"},
	{id:14, text:'Sardinia', value:"1"},
	{id:15, text:'Mexico', value:"1"},
	{id:16, text:'Genoa', value:"1"},
	{id:17, text:'Duchy of Courland', value:"1"},
	{id:18, text:'Prussia', value:"1"},
	{id:19, text:'Bremen', value:"1"},
	{id:20, text:'Other', value:"1"}
]

// flag-imputed
var flagImputedData = [
	{id:0, text:'Spain/Uruguay', value:"1"},
	{id:1, text:'Portugal/Brazil', value:"1"},
	{id:2, text:'Great Britain', value:"1"},
	{id:3, text:'Netherlands', value:"1"},
	{id:4, text:'U.S.A', value:"1"},
	{id:5, text:'France', value:"1"},
	{id:6, text:'U.S.A', value:"1"},
	{id:7, text:'Denmark/Baltic', value:"1"}
]

// rig
var rigData = [
	{id:0, value:"1", text:"Brig"},
	{id:1, value:"2", text:"Schooner"},
	{id:2, value:"3", text:"Curveta"},
	{id:3, value:"4", text:"Ship"},
	{id:4, value:"5", text:"Schooner-brig"},
	{id:5, value:"6", text:"Smack"},
	{id:6, value:"7", text:"Patacho"},
	{id:7, value:"8", text:"Brigantine"},
	{id:8, value:"9", text:"Barque"},
	{id:9, value:"10", text:"Polacca schooner"},
	{id:10, value:"11", text:"Pailebot"},
	{id:11, value:"12", text:"Pilot boat"},
	{id:12, value:"13", text:"Sumaca"},
	{id:13, value:"14", text:"Yacht"},
	{id:14, value:"15", text:"Felucca"},
	{id:15, value:"16", text:"Galliot"},
	{id:16, value:"17", text:"Cutter"},
	{id:17, value:"18", text:"Pinnace"},
	{id:18, value:"19", text:"Launch"},
	{id:19, value:"20", text:"Barqua"},
	{id:20, value:"21", text:"Navio mercante"},
	{id:21, value:"22", text:"Charrua de guerra"},
	{id:22, value:"23", text:"Chalupa"},
	{id:23, value:"24", text:"Pollaca"},
	{id:24, value:"25", text:"Galera"},
	{id:25, value:"26", text:"Vessel"},
	{id:26, value:"27", text:"Sloop"},
	{id:27, value:"28", text:"Steamer"},
	{id:28, value:"29", text:"Whaler"},
	{id:29, value:"30", text:"Fregat"},
	{id:30, value:"31", text:"Barque (Dutch)"},
	{id:31, value:"32", text:"Fluit"},
	{id:32, value:"33", text:"Brik"},
	{id:33, value:"34", text:"Hoeker"},
	{id:34, value:"35", text:"Snauw"},
	{id:35, value:"36", text:"Yaght"},
	{id:36, value:"37", text:"Pinas"},
	{id:37, value:"38", text:"Galjoot"},
	{id:38, value:"39", text:"Hekboot"},
	{id:39, value:"40", text:"Bergantin"},
	{id:40, value:"41", text:"Penque"},
	{id:41, value:"42", text:"Não"},
	{id:42, value:"43", text:"Corsario"},
	{id:43, value:"44", text:"Charrua"},
	{id:44, value:"45", text:"Fregata"},
	{id:45, value:"46", text:"Charrauinha"},
	{id:46, value:"47", text:"Balandra"},
	{id:47, value:"48", text:"Paquete"},
	{id:48, value:"49", text:"Hyate (iate)"},
	{id:49, value:"50", text:"Berlin"},
	{id:50, value:"51", text:"Goleta"},
	{id:51, value:"52", text:"Lugger"},
	{id:52, value:"53", text:"Ketch"},
	{id:53, value:"54", text:"Billd"},
	{id:54, value:"55", text:"Boat"},
	{id:55, value:"56", text:"shallop (a) shalp"},
	{id:56, value:"57", text:"Pink"},
	{id:57, value:"58", text:"Hay"},
	{id:58, value:"59", text:"Dogger"},
	{id:59, value:"60", text:"Buque"},
	{id:60, value:"61", text:"Laud"},
	{id:61, value:"62", text:"Brigue-escuna"},
	{id:62, value:"63", text:"Fragatihna"},
	{id:63, value:"64", text:"Nau caravela"},
	{id:64, value:"65", text:"Lancha"},
	{id:65, value:"66", text:"Talaveira"},
	{id:66, value:"67", text:"Batelão"},
	{id:67, value:"70", text:"Caravela"},
	{id:68, value:"71", text:"Galeão"},
	{id:69, value:"72", text:"Nau-Caravela"},
	{id:70, value:"75", text:"Faluxo"},
	{id:71, value:"76", text:"xixorro"},
	{id:72, value:"77", text:"Vasca"},
	{id:73, value:"80", text:"Pangaio"},
	{id:74, value:"81", text:"Palla"},
	{id:75, value:"82", text:"Barca"},
	{id:76, value:"83", text:"Escaller"},
	{id:77, value:"84", text:"Filibote"},
	{id:78, value:"85", text:"Urca"},
	{id:79, value:"86", text:"Pinnace"},
	{id:80, value:"87", text:"Columpo"},
	{id:81, value:"88", text:"Periagua (a) petty augre"},
	{id:82, value:"89", text:"Broad sterne"},
	{id:83, value:"90", text:"Guardacosta"},
	{id:84, value:"99", text:"Other (specify in note)"}
]
