# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-04 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0002_auto_20200717_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderncountry',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=None, max_digits=10, verbose_name=b'Latitude of Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderncountry',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=None, max_digits=10, verbose_name=b'Longitude of Country'),
            preserve_default=False,
        ),
    ]
