# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0002_auto_20200925_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaved',
            name='editor_modern_names_certainty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
