# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0004_auto_20201125_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslavedcontribution',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
