# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-10-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0006_auto_20211006_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptiveFate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptiveStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='altethnicityname',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='language_group',
        ),
        migrations.RemoveField(
            model_name='enslaved',
            name='captive_status',
        ),
        migrations.RemoveField(
            model_name='enslaved',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='enslavedcontributionlanguageentry',
            name='ethnicity',
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Height in inches'),
        ),
        migrations.DeleteModel(
            name='AltEthnicityName',
        ),
        migrations.DeleteModel(
            name='Ethnicity',
        ),
        migrations.AddField(
            model_name='enslaved',
            name='captive_fate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.CaptiveFate'),
        ),
    ]
