# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-10-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0007_auto_20211018_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaved',
            name='captive_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.CaptiveStatus'),
        ),
    ]
