# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-10-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0008_enslaved_captive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaved',
            name='documented_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='modern_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='name_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='name_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='name_third',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
