# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-11-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0010_auto_20211115_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaved',
            name='age',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='dataset',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='gender',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='height',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, null=True, verbose_name='Height in inches'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='skin_color',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslavedsourceconnection',
            name='enslaved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_conn', to='past.Enslaved'),
        ),
    ]
