# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-11-26 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0011_auto_20211116_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaved',
            name='skin_color',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='enslaved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='past.Enslaved'),
        ),
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved', to='past.EnslavementRelation'),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslavers', to='past.EnslavementRelation'),
        ),
        migrations.AlterField(
            model_name='languagegroup',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True, verbose_name='Latitude of point'),
        ),
        migrations.AlterField(
            model_name='languagegroup',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True, verbose_name='Longitude of point'),
        ),
    ]
