# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-11-19 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0011_auto_20211116_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnslavementRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnslaverRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='enslaveralias',
            name='text_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='first_active_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='last_active_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='number_enslaved',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='text_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='first_active_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='last_active_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='number_enslaved',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='text_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='role',
            field=models.ForeignKey(help_text='The role of the enslaver in this relation', on_delete=django.db.models.deletion.CASCADE, to='past.EnslaverRole'),
        ),
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='past.EnslaverRole'),
        ),
    ]
