# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-01-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0012_auto_20211126_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captivestatus',
            options={'verbose_name': 'Captive status', 'verbose_name_plural': 'Captive statuses'},
        ),
        migrations.AlterModelOptions(
            name='moderncountry',
            options={'verbose_name': 'Modern country', 'verbose_name_plural': 'Modern countries'},
        ),
        migrations.AlterModelOptions(
            name='registercountry',
            options={'verbose_name': 'Register country', 'verbose_name_plural': 'Register countries'},
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='text_id',
            field=models.CharField(default='temp_id', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='text_id',
            field=models.CharField(default='temp_id', max_length=50),
            preserve_default=False,
        ),
    ]
