# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-01-14 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0015_auto_20211116_1650'),
        ('past', '0013_auto_20220104_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnslavementRelationType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnslaverRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnslaverVoyageConnectionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_order', models.IntegerField()),
                ('text_ref', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='enslavedinrelation',
            old_name='transaction',
            new_name='relation',
        ),
        migrations.RenameField(
            model_name='enslaverinrelation',
            old_name='transaction',
            new_name='relation',
        ),
        migrations.RemoveField(
            model_name='enslaveridentity',
            name='first_marriage_date',
        ),
        migrations.RemoveField(
            model_name='enslaveridentity',
            name='first_spouse_name',
        ),
        migrations.RemoveField(
            model_name='enslaveridentity',
            name='second_marriage_date',
        ),
        migrations.RemoveField(
            model_name='enslaveridentity',
            name='second_spouse_name',
        ),
        migrations.RemoveField(
            model_name='enslavermerger',
            name='first_marriage_date',
        ),
        migrations.RemoveField(
            model_name='enslavermerger',
            name='first_spouse_name',
        ),
        migrations.RemoveField(
            model_name='enslavermerger',
            name='second_marriage_date',
        ),
        migrations.RemoveField(
            model_name='enslavermerger',
            name='second_spouse_name',
        ),
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='enslaved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='past.Enslaved'),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='past.EnslavementRelationType'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='probate_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_court',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_value_dollars',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_value_pounds',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='role',
            field=models.ForeignKey(help_text='The role of the enslaver in this relation', on_delete=django.db.models.deletion.CASCADE, to='past.EnslaverRole'),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='probate_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='will_court',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='will_value_dollars',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='will_value_pounds',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='past.EnslaverRole'),
        ),
        migrations.AddField(
            model_name='enslavervoyageconnectionsource',
            name='enlaver_voyage_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='past.EnslaverVoyageConnection'),
        ),
        migrations.AddField(
            model_name='enslavervoyageconnectionsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.VoyageSources'),
        ),
    ]
