# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-02-23 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0015_auto_20211116_1650'),
        ('past', '0015_auto_20220124_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaveridentity',
            name='principal_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voyage.Place'),
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='principal_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voyage.Place'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='probate_date',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_court',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_value_dollars',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_value_pounds',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='probate_date',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='will_court',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='will_value_dollars',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='will_value_pounds',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
