# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-03-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0016_auto_20220223_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enslaveridentity',
            name='text_id',
        ),
        migrations.RemoveField(
            model_name='enslavermerger',
            name='text_id',
        ),
        migrations.AddField(
            model_name='enslaveralias',
            name='manual_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
