# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-03-15 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0017_auto_20220310_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnslaverCachedProperties',
            fields=[
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cached_properties', serialize=False, to='past.EnslaverIdentity', unique=True)),
                ('enslaved_count', models.IntegerField()),
            ],
        ),
    ]
