# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-03-24 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0018_enslavercachedproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslavercachedproperties',
            name='first_year',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enslavercachedproperties',
            name='last_year',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enslavercachedproperties',
            name='roles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enslavercachedproperties',
            name='transactions_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='enslavercachedproperties',
            name='enslaved_count',
            field=models.IntegerField(db_index=True),
        ),
    ]
