# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0020_enslavercachedproperties_voyage_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavercachedproperties',
            name='identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cached_properties', serialize=False, to='past.EnslaverIdentity'),
        ),
    ]
