# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-08-12 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0021_auto_20220621_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enslavedcontributionlanguageentry',
            name='notes',
        ),
    ]
