# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-08-23 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0022_remove_enslavedcontributionlanguageentry_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaveridentity',
            name='notes',
            field=models.CharField(max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='enslavermerger',
            name='notes',
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
