# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-08-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0023_auto_20220823_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enslavermerger',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='enslavermerger',
            name='death_place',
        ),
        migrations.RemoveField(
            model_name='enslavermerger',
            name='principal_location',
        ),
        migrations.RemoveField(
            model_name='enslavermergeritem',
            name='merger',
        ),
        migrations.AddField(
            model_name='enslaved',
            name='modern_country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='past.ModernCountry'),
        ),
        migrations.AddField(
            model_name='enslavedcontributionlanguageentry',
            name='modern_country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='past.ModernCountry'),
        ),
        migrations.DeleteModel(
            name='EnslaverMerger',
        ),
        migrations.DeleteModel(
            name='EnslaverMergerItem',
        ),
    ]
