# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-11-05 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('past', '0024_auto_20220830_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnslaverContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('data', models.TextField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enslaver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.EnslaverIdentity')),
            ],
        ),
    ]
