# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-11-30 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0025_enslavercontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslavementrelation',
            name='unnamed_enslaved_count',
            field=models.IntegerField(null=True),
        ),
    ]
