# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-02-14 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0026_enslavementrelation_unnamed_enslaved_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enslaved',
            name='modern_country',
        ),
        migrations.RemoveField(
            model_name='enslavedcontributionlanguageentry',
            name='modern_country',
        ),
    ]
