# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-02-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0026_enslavementrelation_unnamed_enslaved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaveridentity',
            name='is_natural_person',
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            sql=["UPDATE past_enslaveridentity SET is_natural_person=FALSE WHERE principal_alias LIKE '% company%' OR principal_alias LIKE '%company of%' OR principal_alias LIKE '%compania%' OR principal_alias LIKE '%companhia%' OR principal_alias LIKE '%compagnie%'"],
            reverse_sql=[])
    ]
