# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-02-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0027_auto_20230214_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslavercachedproperties',
            name='max_alias',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enslavercachedproperties',
            name='min_alias',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
