# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-05-25 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0028_auto_20230216_1250'),
        ('past', '0027_enslaveridentity_is_natural_person'),
    ]

    operations = [
    ]
