# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-02-18 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [        
        ('blog', '0001_initial'),
    ]

    operations = [        
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]