# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-02-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
