# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-04-01 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220401_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='role',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
