# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-04-15 04:04
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=300, null=True, verbose_name='Image'),
        ),
    ]
