# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-04-20 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=300, null=True, verbose_name='Thumbnail'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('slug', 'language')]),
        ),
    ]
