# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-04-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('thumbnail', filebrowser.fields.FileBrowseField(blank=True, max_length=300, null=True, verbose_name='Thumbnail')),
                ('authors', models.ManyToManyField(to='blog.Author')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=300, null=True, verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_translations', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
