# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-04-20 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220420_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
