# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-04-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_posttranslation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.Post'),
        ),
    ]
