# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-04-21 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220420_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttranslation',
            name='authors',
        ),
    ]
