//truly absurd. the db table is called "language_groups" for god's sake

var clustered_dialects={
	'Yoruba':'Yoruba',
	'Yoruba-Awori':'Yoruba',
	'Yoruba-Egba':'Yoruba',
	'Yoruba-Egbado':'Yoruba',
	'Yoruba-Ekiti':'Yoruba',
	'Yoruba-Ife':'Yoruba',
	'Yoruba-Ijebu':'Yoruba',
	'Yoruba-Ijeshi':'Yoruba',
	'Yoruba-Itsekiri':'Yoruba',
	'Yoruba-Ondo':'Yoruba',
	'Yoruba-Oyo':'Yoruba',
	'Yoruba-Yagba':'Yoruba',
	'Igbo':'Igbo',
	'Igbo-Nkalagu':'Igbo',
	'Igbo-Nri':'Igbo',
	'Igbo-Orlu':'Igbo',
	'Igbo-Nsukka':'Igbo',
	'Igbo-Oguta':'Igbo',
	'Igbo-Onitsha':'Igbo',
	'Igbo-Owerri':'Igbo',
	'Igbo-Umuahia':'Igbo',
	'Ijo or Igbo':'Igbo',
	'Bakossi or Igbo':'Igbo',
	'Bakweri or Igbo':'Igbo',
	'Duala or Igbo':'Igbo',
	'Ejagham or Igbo':'Igbo',
	'Igbo or Ibibio':'Igbo',
	'Igbo or Igala':'Igbo',
	'Igbo or Ogoja':'Igbo',
	'Igbo Ogoni':'Igbo',
	'Igbo-Abariba':'Igbo',
	'Igbo-Aguleci':'Igbo',
	'Igbo-Awka':'Igbo',
	'Igbo-Mbano':'Igbo',
	'Igbo-Ngwa':'Igbo',
	'Etcie or Igbo':'Igbo',
	'Tiv or Igbo':'Igbo',
	'Urhobo or Igbo':'Igbo',
	'Yako or Igbo':'Igbo'
}