var tabs = {
  tables: {
    controls: {
      row: {
        options: [{id: 0, label: "Flag*"},
        {id: 1, label: "Broad region where voyage began"},
        {id: 2, label: "Region where voyage began"},
        {id: 3, label: "Port where voyage began"},
        {id: 4, label: "Embarkation Regions"},
        {id: 5, label: "Embarkation Ports"},
        {id: 6, label: "Specific regions of disembarkation"},
        {id: 7, label: "Broad regions of disembarkation"},
        {id: 8, label: "Disembarkation Ports"},
        {id: 9, label: "Individual Years"},
        {id: 10, label: "5-year periods"},
        {id: 11, label: "10-year periods"},
        {id: 12, label: "25-year periods"},
        {id: 13, label: "50-year periods"},
        {id: 14, label: "100-year periods"}],
      },
      column: {
        options: [{id: 0, label: "Flag*"},
          {id: 1, label: "Broad region where voyage began"},
          {id: 2, label: "Region where voyage began"},
          {id: 3, label: "Port where voyage began"},
          {id: 4, label: "Embarkation Regions"},
          {id: 5, label: "Embarkation Ports"},
          {id: 6, label: "Specific regions of disembarkation"},
          {id: 7, label: "Broad regions of disembarkation"},
          {id: 8, label: "Disembarkation Ports"}],
      },
      cell: {
        options: [{id: 0, label: "Number of Voyages"},
        {id: 1, label: "Sum of embarked slaves"},
        {id: 2, label: "Average number of embarked slaves"},
        {id: 3, label: "Number of voyages - embarked slaves"},
        {id: 4, label: "Percent of embarked slaves (row total)"},
        {id: 5, label: "Percent of embarked slaves (column total)"},
        {id: 6, label: "Sum of disembarked slaves"},
        {id: 7, label: "Average number of disembarked slaves"},
        {id: 8, label: "Number of voyages - disembarked slaves"},
        {id: 9, label: "Percent of disembarked slaves (row total)"},
        {id: 10, label: "Percent of disembarked slaves (column total)"},
        {id: 11, label: "Sum of embarked/disembarked slaves"},
        {id: 12, label: "Average number of embarked/disembarked slaves"},
        {id: 13, label: "Number of voyages - embarked/disembarked slaves"},
        {id: 14, label: "Average percentage male"},
        {id: 15, label: "Number of voyages - percentage male"},
        {id: 16, label: "Average percentage children"},
        {id: 17, label: "Number of voyages - percentage children"},
        {id: 18, label: "Average percentage of slaves embarked who died during voyage"},
        {id: 19, label: "Number of voyages - percentage of slaves embarked who died during voyage"},
        {id: 20, label: "Average middle passage (days)"},
        {id: 21, label: "Number of voyages - middle passage (days)"},
        {id: 22, label: "Average standarized tonnage"},
        {id: 23, label: "Number of voyages - standarized tonnage"},
        {id: 24, label: "Sterling cash price in Jamaica"},
        {id: 25, label: "Number of voyages - sterling cash price in Jamaica"}],
      },
    },
  },
}
