var tabs = {
  // Tables Tab
  tables: {
    row: {
      // currently selected value
      variable: "tabs.tables.row",
      value: null,
      options: [{id: 0, label: "Flag*"},
      {id: 1, label: "Broad region where voyage began"},
      {id: 2, label: "Region where voyage began"},
      {id: 3, label: "Port where voyage began"},
      {id: 4, label: "Embarkation Regions"},
      {id: 5, label: "Embarkation Ports"},
      {id: 6, label: "Specific regions of disembarkation"},
      {id: 7, label: "Broad regions of disembarkation"},
      {id: 8, label: "Disembarkation Ports"},
      {id: 9, label: "Individual Years"},
      {id: 10, label: "5-year periods"},
      {id: 11, label: "10-year periods"},
      {id: 12, label: "25-year periods"},
      {id: 13, label: "50-year periods"},
      {id: 14, label: "100-year periods"}],
    },
    column: {
      // currently selected value
      variable: "tabs.tables.column",
      value: null,
      options: [{id: 0, label: "Flag*"},
        {id: 1, label: "Broad region where voyage began"},
        {id: 2, label: "Region where voyage began"},
        {id: 3, label: "Port where voyage began"},
        {id: 4, label: "Embarkation Regions"},
        {id: 5, label: "Embarkation Ports"},
        {id: 6, label: "Specific regions of disembarkation"},
        {id: 7, label: "Broad regions of disembarkation"},
        {id: 8, label: "Disembarkation Ports"}],
    },
    cell: {
      // currently selected value
      variable: "tabs.tables.cell",
      value: null,
      options: [{id: 0, label: "Number of Voyages"},
      {id: 1, label: "Sum of embarked slaves"},
      {id: 2, label: "Average number of embarked slaves"},
      {id: 3, label: "Number of voyages - embarked slaves"},
      {id: 4, label: "Percent of embarked slaves (row total)"},
      {id: 5, label: "Percent of embarked slaves (column total)"},
      {id: 6, label: "Sum of disembarked slaves"},
      {id: 7, label: "Average number of disembarked slaves"},
      {id: 8, label: "Number of voyages - disembarked slaves"},
      {id: 9, label: "Percent of disembarked slaves (row total)"},
      {id: 10, label: "Percent of disembarked slaves (column total)"},
      {id: 11, label: "Sum of embarked/disembarked slaves"},
      {id: 12, label: "Average number of embarked/disembarked slaves"},
      {id: 13, label: "Number of voyages - embarked/disembarked slaves"},
      {id: 14, label: "Average percentage male"},
      {id: 15, label: "Number of voyages - percentage male"},
      {id: 16, label: "Average percentage children"},
      {id: 17, label: "Number of voyages - percentage children"},
      {id: 18, label: "Average percentage of slaves embarked who died during voyage"},
      {id: 19, label: "Number of voyages - percentage of slaves embarked who died during voyage"},
      {id: 20, label: "Average middle passage (days)"},
      {id: 21, label: "Number of voyages - middle passage (days)"},
      {id: 22, label: "Average standarized tonnage"},
      {id: 23, label: "Number of voyages - standarized tonnage"},
      {id: 24, label: "Sterling cash price in Jamaica"},
      {id: 25, label: "Number of voyages - sterling cash price in Jamaica"}],
    },
  },

  // Data Visualization Tab
  visualization: {
    scatter: {
      x: {
        // currently selected value
        variable: "tabs.visualization.scatter.x",
        value: null,
        options: [{id: 0, label: "Flag*"},
        {id: 1, label: "Broad region where voyage began"},
        {id: 2, label: "Region where voyage began"},
        {id: 3, label: "Port where voyage began"},
        {id: 4, label: "Embarkation Regions"},
        {id: 5, label: "Embarkation Ports"},
        {id: 6, label: "Specific regions of disembarkation"},
        {id: 7, label: "Broad regions of disembarkation"},
        {id: 8, label: "Disembarkation Ports"},
        {id: 9, label: "Individual Years"},
        {id: 10, label: "5-year periods"},
        {id: 11, label: "10-year periods"},
        {id: 12, label: "25-year periods"},
        {id: 13, label: "50-year periods"},
        {id: 14, label: "100-year periods"}],
      },
      y: {
        // currently selected value
        variable: "tabs.visualization.scatter.y",
        value: null,
        options: [{id: 0, label: "Flag*"},
          {id: 1, label: "Broad region where voyage began"},
          {id: 2, label: "Region where voyage began"},
          {id: 3, label: "Port where voyage began"},
          {id: 4, label: "Embarkation Regions"},
          {id: 5, label: "Embarkation Ports"},
          {id: 6, label: "Specific regions of disembarkation"},
          {id: 7, label: "Broad regions of disembarkation"},
          {id: 8, label: "Disembarkation Ports"}],
      },
    },
    bar: {
      x: {
        // currently selected value
        variable: "tabs.visualization.bar.x",
        value: null,
        options: [{id: 0, label: "Flag*"},
        {id: 1, label: "Broad region where voyage began"},
        {id: 2, label: "Region where voyage began"},
        {id: 3, label: "Port where voyage began"},
        {id: 4, label: "Embarkation Regions"},
        {id: 5, label: "Embarkation Ports"},
        {id: 6, label: "Specific regions of disembarkation"},
        {id: 7, label: "Broad regions of disembarkation"},
        {id: 8, label: "Disembarkation Ports"},
        {id: 9, label: "Individual Years"},
        {id: 10, label: "5-year periods"},
        {id: 11, label: "10-year periods"},
        {id: 12, label: "25-year periods"},
        {id: 13, label: "50-year periods"},
        {id: 14, label: "100-year periods"}],
      },
      y: {
        // currently selected value
        variable: "tabs.visualization.bar.y",
        value: null,
        options: [{id: 0, label: "Flag*"},
          {id: 1, label: "Broad region where voyage began"},
          {id: 2, label: "Region where voyage began"},
          {id: 3, label: "Port where voyage began"},
          {id: 4, label: "Embarkation Regions"},
          {id: 5, label: "Embarkation Ports"},
          {id: 6, label: "Specific regions of disembarkation"},
          {id: 7, label: "Broad regions of disembarkation"},
          {id: 8, label: "Disembarkation Ports"}],
      },
    },
    donut: {
      sectors: {
        // currently selected value
        variable: "tabs.visualization.donut.sectors",
        value: null,
        options: [{id: 0, label: "Flag*"},
        {id: 1, label: "Broad region where voyage began"},
        {id: 2, label: "Region where voyage began"},
        {id: 3, label: "Port where voyage began"},
        {id: 4, label: "Embarkation Regions"},
        {id: 5, label: "Embarkation Ports"},
        {id: 6, label: "Specific regions of disembarkation"},
        {id: 7, label: "Broad regions of disembarkation"},
        {id: 8, label: "Disembarkation Ports"},
        {id: 9, label: "Individual Years"},
        {id: 10, label: "5-year periods"},
        {id: 11, label: "10-year periods"},
        {id: 12, label: "25-year periods"},
        {id: 13, label: "50-year periods"},
        {id: 14, label: "100-year periods"}],
      },
      values: {
        // currently selected value
        variable: "tabs.visualization.donut.values",
        value: null,
        options: [{id: 0, label: "Flag*"},
          {id: 1, label: "Broad region where voyage began"},
          {id: 2, label: "Region where voyage began"},
          {id: 3, label: "Port where voyage began"},
          {id: 4, label: "Embarkation Regions"},
          {id: 5, label: "Embarkation Ports"},
          {id: 6, label: "Specific regions of disembarkation"},
          {id: 7, label: "Broad regions of disembarkation"},
          {id: 8, label: "Disembarkation Ports"}],
      },
    },
  },

  // Timeline Tab
  timeline: {
    chart: {
      // currently selected value
      variable: "tabs.timeline.chart",
      value: null,
      options: [{id: 0, label: "Number of voyages"},
      {id: 1, label: "Average tonnage"},
      {id: 2, label: "Average tonnage (standardized)"},
      {id: 3, label: "Average number of guns"},
      {id: 4, label: "Rate of resistance"},
      {id: 5, label: "Average duration of voyage from home port to disembarkation (days)"},
      {id: 6, label: "Average duration of middle passage (days)"},
      {id: 7, label: "Average crew at outset"},
      {id: 8, label: "Average crew at first landing of slaves"},
      {id: 9, label: "Number of crew deaths"},
      {id: 10, label: "Average crew deaths"},
      {id: 11, label: "Intended number of purchases"},
      {id: 12, label: "Average intended purchases"},
      {id: 13, label: "Total number of captives embarked"},
      {id: 14, label: "Average number of captives embarked"},
      {id: 15, label: "Total number of captives disembarked"},
      {id: 16, label: "Average number of captives disembarked"},
      {id: 17, label: "Percentage men (among captives)"},
      {id: 18, label: "Percentage women (among captives)"},
      {id: 19, label: "Percentage boys (among captives)"},
      {id: 20, label: "Percentage girls (among captives)"},
      {id: 21, label: "Percentage female (among captives)"},
      {id: 22, label: "Percentage male (among captives)"},
      {id: 23, label: "Sterling cash price in Jamaica*"},
      {id: 24, label: "Number of slave deaths"},
      {id: 25, label: "Average slave deaths"},
      {id: 26, label: "Average percentage of slaves embarked who died during the voyage"}],
    },
  },
}
