# List of basic variables

list_text_fields = ['var_ship_name',
                    'var_owner',
                    'var_captain',
                    'var_sources']
list_select_fields = ['var_nationality',
                      'var_imputed_nationality',
                      'var_outcome_voyage',
                      'var_outcome_slaves',
                      'var_outcome_owner',
                      'var_resistance',
                      'var_outcome_ship_captured',
                      ]
list_numeric_fields = ['var_voyage_id',
                       'var_year_of_construction',
                       'var_registered_year',
                       'var_rig_of_vessel',
                       'var_guns_mounted',

                       # Voyage dates variables
                       'var_imp_arrival_at_port_of_dis',  # Year arrived with salves
                       'var_imp_length_home_to_disembark',
                       'var_length_middle_passage_days',

                       'var_crew_voyage_outset',
                       'var_crew_first_landing',
                       'var_crew_died_complete_voyage',
                       'var_num_slaves_intended_first_port',
                       'var_num_slaves_carried_first_port',
                       'var_num_slaves_carried_second_port',
                       'var_num_slaves_carried_third_port',
                       'var_total_num_slaves_purchased',
                       'var_imp_total_num_slaves_purchased',
                       'var_total_num_slaves_arr_first_port_embark',
                       'var_num_slaves_disembark_first_place',
                       'var_num_slaves_disembark_second_place',
                       'var_num_slaves_disembark_third_place',
                       'var_imp_total_slaves_disembarked',

                       # Possible change the below to decimal fields
                       'var_tonnage',
                       'var_tonnage_mod',

                       'var_imputed_percentage_men',
                       'var_imputed_percentage_women',
                       'var_imputed_percentage_boys',
                       'var_imputed_percentage_girls',
                       'var_imputed_percentage_female',
                       'var_imputed_percentage_male',
                       'var_imputed_percentage_child',
                       'var_imputed_sterling_cash',
                       'var_imputed_death_middle_passage',
                       'var_imputed_mortality'
                       ]

list_date_fields = ['var_voyage_began',
                    'var_slave_purchase_began',
                    'var_vessel_left_port',
                    'var_first_dis_of_slaves',
                    'var_departure_last_place_of_landing',
                    'var_voyage_completed'
                    ]

list_place_fields = ['var_vessel_construction_place',
                     'var_registered_place',
                     'var_imp_port_voyage_begin',
                     'var_first_place_slave_purchase',
                     'var_second_place_slave_purchase',
                     'var_third_place_slave_purchase',
                     'var_imp_principal_place_of_slave_purchase',
                     'var_port_of_call_before_atl_crossing',
                     'var_first_landing_place',
                     'var_second_landing_place',
                     'var_third_landing_place',
                     'var_principal_port_of_slave_dis',
                     'var_place_voyage_ended',
                     ]

list_boolean_fields = ['var_voyage_in_cd_rom']

list_imputed_nationality_values = ['Spain / Uruguay', 'Portugal / Brazil', 'Great Britain',
                                   'Netherlands', 'U.S.A', 'France', 'Denmark / Baltic',
                                   'Other (specify in note)']

list_months = [('Jan', '01'), ('Feb', '02'), ('Mar', '03'), ('Apr', '04'), ('May', '05'), ('Jun', '06'),
               ('Jul', '07'), ('Aug', '08'), ('Sep', '09'), ('Oct', '10'), ('Nov', '11'), ('Dec', '12')]

var_dict = [
    # Ship, Nation, Owners
    {'var_name': 'var_voyage_id',
     'spss_name': 'voyageid',
     'var_full_name': 'Voyage identification number',
     'var_type': 'numeric',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True},
    {'var_name': 'var_voyage_in_cd_rom',
     'spss_name': 'evgreen',
     'var_full_name': 'Voyage in 1999 CD-ROM',
     'var_type': 'boolean',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_ship_name',
     'spss_name': 'shipname',
     'var_full_name': 'Vessel name',
     'var_type': 'plain_text',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True},
    {'var_name': 'var_nationality',
     'spss_name': 'national',
     'var_full_name': 'Flag',
     'var_type': 'select',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_imputed_nationality',
     'spss_name': 'natinimp',
     'var_full_name': 'Flag' + "*",
     'var_type': 'select',
     'var_category': 'Ship, nation, owners',
     "is_estimate": True,
     "is_basic": True,
     "is_general": True,
     "note" : "Flag regrouped into seven major national carriers"},
    {'var_name': 'var_vessel_construction_place',
     'spss_name': 'placcons',
     'var_full_name': 'Place constructed',
     'var_type': 'select_three_layers',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_year_of_construction',
     'spss_name': 'yrcons',
     'var_full_name': 'Year constructed',
     'var_type': 'numeric',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_registered_place',
     'spss_name': 'placreg',
     'var_full_name': 'Place registered',
     'var_type': 'select_three_layers',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_registered_year',
     'spss_name': 'yrreg',
     'var_full_name': 'Year registered',
     'var_type': 'numeric',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_rig_of_vessel',
     'spss_name': 'yrreg',
     'var_full_name': 'Rig',
     'var_type': 'numeric',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_tonnage',
     'spss_name': 'tonnage',
     'var_full_name': 'Tonnage',
     'var_type': 'numeric',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_tonnage_mod',
     'spss_name': 'tonmod',
     'var_full_name': 'Standardized tonnage',
     'var_type': 'numeric',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note": "Converted to pre-1786 British registered tons"},
    {'var_name': 'var_guns_mounted',
     'spss_name': 'guns',
     'var_full_name': 'Guns mounted',
     'var_type': 'numeric',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_owner',
     'spss_name': 'owner',
     'var_full_name': 'Vessel owners',
     'var_type': 'plain_text',
     'var_category': 'Ship, nation, owners',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True},

    # Voyage outcome
    {'var_name': 'var_outcome_voyage',
     'spss_name': 'fate',
     'var_full_name': 'Particular outcome of voyage',
     'var_type': 'select',
     'var_category': 'Voyage Outcome',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_outcome_slaves',
     'spss_name': 'fate2',
     'var_full_name': 'Outcome of voyage for slaves*',
     'var_type': 'select',
     'var_category': 'Voyage Outcome',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True,
     "note": "Derived from particular outcome"},
    {'var_name': 'var_outcome_ship_captured',
     'spss_name': 'fate3',
     'var_full_name': 'Outcome of voyage if ship captured*',
     'var_type': 'select',
     'var_category': 'Voyage Outcome',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note": "Derived from particular outcome"},
    {'var_name': 'var_outcome_owner',
     'spss_name': 'fate4',
     'var_full_name': 'Outcome of voyage for owner*',
     'var_type': 'select',
     'var_category': 'Voyage Outcome',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True,
     "note": "Derived from particular outcome"},
    {'var_name': 'var_resistance',
     'spss_name': 'resistance',
     'var_full_name': 'African resistance',
     'var_type': 'select',
     'var_category': 'Voyage Outcome',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True},

    # Voyage Itinerary
    {'var_name': 'var_imp_port_voyage_begin',
     'spss_name': 'ptdepimp',
     'var_full_name': 'Place where voyage began',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True,
     "note": "Same as data variable in most cases, but derived from "
             "port of return for certain Brazilian voyages"},

    {'var_name': 'var_first_place_slave_purchase',
     'spss_name': 'plac1tra',
     'var_full_name': 'First place of slave purchase',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},

    {'var_name': 'var_second_place_slave_purchase',
     'spss_name': 'plac2tra',
     'var_full_name': 'Second place of slave purchase',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},

    {'var_name': 'var_third_place_slave_purchase',
     'spss_name': 'plac3tra',
     'var_full_name': 'Third place of slave purchase',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},

    {'var_name': 'var_imp_principal_place_of_slave_purchase',
     'spss_name': 'mjbyptimp',
     'var_full_name': 'Principal place of slave purchase*',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": True,
     "is_basic": True,
     "is_general": True,
     "note": "Place where largest number of captives embarked"},

    {'var_name': 'var_port_of_call_before_atl_crossing',
     'spss_name': 'npafttra',
     'var_full_name': 'Places of call before Atlantic crossing',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},

    {'var_name': 'var_first_landing_place',
     'spss_name': 'sla1port',
     'var_full_name': 'First place of slave landing',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},

    {'var_name': 'var_second_landing_place',
     'spss_name': 'adpsale1',
     'var_full_name': 'Second place of slave landing',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},

    {'var_name': 'var_third_landing_place',
     'spss_name': 'adpsale2',
     'var_full_name': 'Third place of slave landing',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},

    {'var_name': 'var_imp_principal_port_of_slave_dis',
     'spss_name': 'mjslptimp',
     'var_full_name': 'Principal place of slave landing*',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": True,
     "is_basic": True,
     "is_general": True,
     "note": "Place where largest number of captives embarked"},

    {'var_name': 'var_place_voyage_ended',
     'spss_name': 'portret',
     'var_full_name': 'Place where voyage ended',
     'var_type': 'select_three_layers',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},

    # Itinerary - region variables
    {'var_name': 'var_imp_region_voyage_begin',
     'spss_name': 'deptregimp',
     'var_full_name': 'Region where voyage began*',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},

    {'var_name': 'var_first_region_slave_emb',
     'spss_name': 'regem1',
     'var_full_name': 'First region of slave purchase',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},


    {'var_name': 'var_second_region_slave_emb',
     'spss_name': 'regem2',
     'var_full_name': 'Second region of slave purchase',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},

    {'var_name': 'var_third_region_slave_emb',
     'spss_name': 'regem3',
     'var_full_name': 'Third region of slave purchase',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},

    {'var_name': 'var_imp_principal_region_of_slave_purchase',
     'spss_name': 'majbyimp',
     'var_full_name': 'Principal region of slave purchase*',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},

    {'var_name': 'var_first_landing_region',
     'spss_name': 'regdis1',
     'var_full_name': 'First region of slave landing',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},

    {'var_name': 'var_second_landing_region',
     'spss_name': 'regdis2',
     'var_full_name': 'Second region of slave landing',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},

    {'var_name': 'var_third_landing_region',
     'spss_name': 'regdis3',
     'var_full_name': 'Third region of slave landing',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},

    {'var_name': 'var_imp_principal_region_slave_dis',
     'spss_name': 'mjselimp',
     'var_full_name': 'Principal region of slave landing*',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},

    {'var_name': 'var_region_voyage_ended',
     'spss_name': 'retrnreg',
     'var_full_name': 'Region where voyage ended',
     'var_category': 'Voyage Itinerary',
     "is_estimate": False,
     "is_basic": False,
     "is_general": False},

    # Voyage Dates
    {'var_name': 'var_imp_arrival_at_port_of_dis',
     'spss_name': 'yearam',
     'var_full_name': 'Year arrived with slaves*',
     'var_type': 'numeric',
     'var_category': 'Voyage Dates',
     "is_estimate": True,
     "is_basic": True,
     "is_general": True,
     "note": "Standard variable for classification by year of voyage"},
    {'var_name': 'var_voyage_began',
     'spss_name': 'date_dep',
     'var_full_name': 'Date voyage began',
     'var_type': 'date',
     'var_category': 'Voyage Dates',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_slave_purchase_began',
     'spss_name': 'date_buy',
     'var_full_name': 'Date trade began in Africa',
     'var_type': 'date',
     'var_category': 'Voyage Dates',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_vessel_left_port',
     'spss_name': 'date_leftAfr',
     'var_full_name': 'Date vessel departed Africa',
     'var_type': 'date',
     'var_category': 'Voyage Dates',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_first_dis_of_slaves',
     'spss_name': 'date_land1',
     'var_full_name': 'Date vessel arrived with slaves',
     'var_type': 'date',
     'var_category': 'Voyage Dates',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_departure_last_place_of_landing',
     'spss_name': 'date_depam',
     'var_full_name': 'Date vessel departed for homeport',
     'var_type': 'date',
     'var_category': 'Voyage Dates',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_voyage_completed',
     'spss_name': 'date_end',
     'var_full_name': 'Date voyage completed',
     'var_type': 'date',
     'var_category': 'Voyage Dates',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_imp_length_home_to_disembark',
     'spss_name': 'voy1imp',
     'var_full_name': 'Voyage length, homeport to slaves landing (days)',
     'var_type': 'numeric',
     'var_category': 'Voyage Dates',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note": "Difference between date voyage began and date vessel "
             "arrived with slaves"},
    {'var_name': 'var_length_middle_passage_days',
     'spss_name': 'voy2imp',
     'var_full_name': 'Middle passage (days)',
     'var_type': 'numeric',
     'var_category': 'Voyage Dates',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note": "Difference between date vessel left Africa "
             "and date it arrived with slaves"},
    # Captain and Crew
    {'var_name': 'var_captain',
     'spss_name': 'captain',
     'var_full_name': 'Captain\'s name',
     'var_type': 'plain_text',
     'var_category': 'Captain and Crew',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True},
    {'var_name': 'var_crew_voyage_outset',
     'spss_name': 'crew1',
     'var_full_name': 'Crew at voyage outset',
     'var_type': 'numeric',
     'var_category': 'Captain and Crew',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_crew_first_landing',
     'spss_name': 'crew3',
     'var_full_name': 'Crew at first landing of slaves',
     'var_type': 'numeric',
     'var_category': 'Captain and Crew',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True},
    {'var_name': 'var_crew_died_complete_voyage',
     'spss_name': 'crewdied',
     'var_full_name': 'Crew deaths during voyage',
     'var_type': 'numeric',
     'var_category': 'Captain and Crew',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True},

    # Slaves (numbers)
    {'var_name': 'var_num_slaves_intended_first_port',
     'spss_name': 'slintend',
     'var_full_name': 'Number of slaves intended at first place of purchase',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_num_slaves_carried_first_port',
     'spss_name': 'ncar13',
     'var_full_name': 'Slaves carried from first port of purchase',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_num_slaves_carried_second_port',
     'spss_name': 'ncar15',
     'var_full_name': 'Slaves carried from second port of purchase',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_num_slaves_carried_third_port',
     'spss_name': 'ncar17',
     'var_full_name': 'Slaves carried from third port of purchase',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_total_num_slaves_purchased',
     'spss_name': 'tslavesd',
     'var_full_name': 'Total slaves embarked',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_imp_total_num_slaves_purchased',
     'spss_name': 'slaximp',
     'var_full_name': 'Total slaves embarked*',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": True,
     "is_basic": True,
     "is_general": True,
     "note": "Estimated embarkations"},
    {'var_name': 'var_total_num_slaves_arr_first_port_embark',
     'spss_name': 'slaarriv',
     'var_full_name': 'Number of slaves arriving at first place of landing',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_num_slaves_disembark_first_place',
     'spss_name': 'slas32',
     'var_full_name': 'Number of slaves disembarked at first place of landing',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_num_slaves_disembark_second_place',
     'spss_name': 'slas36',
     'var_full_name': 'Number of slaves disembarked at second place of landing',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_num_slaves_disembark_third_place',
     'spss_name': 'slas39',
     'var_full_name': 'Number of slaves disembarked at third place of landing',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_imp_total_slaves_disembarked',
     'spss_name': 'slamimp',
     'var_full_name': 'Total slaves disembarked*',
     'var_type': 'numeric',
     'var_category': 'Slave (numbers)',
     "is_estimate": True,
     "is_basic": True,
     "is_general": True,
     "note": "Estimated embarkations"},

    # Slaves (characteristics)
    {'var_name': 'var_imputed_percentage_men',
     'spss_name': 'menrat7',
     'var_full_name': 'Percentage men*',
     'var_type': 'numeric',
     'var_category': 'Slave (characteristics)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note" : "Captives identified by age and gender"},
    {'var_name': 'var_imputed_percentage_women',
     'spss_name': 'womrat7',
     'var_full_name': 'Percentage women*',
     'var_type': 'numeric',
     'var_category': 'Slave (characteristics)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note" : "Captives identified by age and gender"},
    {'var_name': 'var_imputed_percentage_boys',
     'spss_name': 'boyrat7',
     'var_full_name': 'Percentage boys*',
     'var_type': 'numeric',
     'var_category': 'Slave (characteristics)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note" : "Captives identified by age and gender"},
    {'var_name': 'var_imputed_percentage_girls',
     'spss_name': 'girlrat7',
     'var_full_name': 'Percentage girls*',
     'var_type': 'numeric',
     'var_category': 'Slave (characteristics)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note" : "Captives identified by age and gender"},
    {'var_name': 'var_imputed_percentage_male',
     'spss_name': 'chilrat7',
     'var_full_name': 'Percentage male*',
     'var_type': 'numeric',
     'var_category': 'Slave (characteristics)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note" : "Captives identified by gender (males/females)"},
    {'var_name': 'var_imputed_percentage_child',
     'spss_name': '',
     'var_full_name': 'Percentage children*',
     'var_type': 'numeric',
     'var_category': 'Slave (characteristics)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note" : "Captives identified by age group (adults/children)"},
    {'var_name': 'var_imputed_sterling_cash',
     'spss_name': 'jamcaspr',
     'var_full_name': 'Sterling cash price in Jamaica*',
     'var_type': 'numeric',
     'var_category': 'Slave (characteristics)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True},
    {'var_name': 'var_imputed_death_middle_passage',
     'spss_name': 'vymrtimp',
     'var_full_name': 'Slave deaths during middle passage*',
     'var_type': 'numeric',
     'var_category': 'Slave (characteristics)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note": "Documented or difference between embarked "
             "and disembarked captives (data variables)"},
    {'var_name': 'var_imputed_mortality',
     'spss_name': 'vymrtrat',
     'var_full_name': 'Mortality rate*',
     'var_type': 'numeric',
     'var_category': 'Slave (characteristics)',
     "is_estimate": False,
     "is_basic": False,
     "is_general": True,
     "note": "Slave deaths during Middle Passage divided by number of "
             "captives leaving Africa"},

    # Source
    {'var_name': 'var_sources',
     'spss_name': 'vymrtrat',
     'var_full_name': 'Sources',
     'var_type': 'plain_text',
     'var_category': 'Source',
     "is_estimate": False,
     "is_basic": True,
     "is_general": True}
]

paginator_range_factors = [-4, -3, -2, -1, 0, 1, 2, 3, 4]
option_results_per_page = [10, 15, 20, 30, 50, 100, 200]

basic_variables = []
for item in var_dict:
    if item['is_basic'] == True:
        basic_variables.append(item)

# List of default result columns
default_result_columns = [
    'var_voyage_id',
    'var_ship_name',
    'var_captain',
    'var_imp_arrival_at_port_of_dis',
    'var_imp_principal_region_of_slave_purchase',
    'var_imp_principal_region_slave_dis',
]