# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquery',
            name='is_legacy',
            field=models.BooleanField(default=True),
        ),
    ]
