# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 17:53
from __future__ import unicode_literals

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_voyage_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagedates',
            name='arrival_at_second_place_landing',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Date of arrival at second place of landing '
                             b'(DATARR37,36,38)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='date_departed_africa',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Date vessel departed Africa (DATELEFTAFR)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='departure_last_place_of_landing',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Date of departure from last place of landing '
                             b'(DDEPAMB,*,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='first_dis_of_slaves',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Date of first disembarkation of slaves '
                             b'(DATARR33,32,34)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='imp_arrival_at_port_of_dis',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Year of arrival at port of disembarkation '
                             b'(YEARAM)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='imp_departed_africa',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Year departed Africa'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='imp_voyage_began',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Year voyage began'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='slave_purchase_began',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Date that slave purchase began (D1SLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='third_dis_of_slaves',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Date of third disembarkation of slaves '
                             b'(DATARR40,39,41)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='vessel_left_port',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Date that vessel left last slaving port '
                             b'(DLSLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_began',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Date that voyage began (DATEDEPB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_completed',
            field=models.CharField(
                blank=True,
                help_text=b'Date in format: MM,DD,YYYY',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:\\,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.')
                ],
                verbose_name=b'Date on which slave voyage completed '
                             b'(DATARR44,43,45)'),
        ),
    ]
