# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0010_linkedvoyages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedvoyages',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to_other_voyages', to='voyage.Voyage'),
        ),
    ]
