# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-09 15:33
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0012_auto_20190527_1359'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='voyage',
            managers=[
                ('both_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='voyageslavesnumbers',
            name='imp_mortality_ratio',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name=b'Imputed mortality ratio (VYMRTRAT)'),
        ),
        migrations.AlterField(
            model_name='voyageslavesnumbers',
            name='percentage_boy',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name=b'Percentage boy on voyage (BOYRAT7)'),
        ),
        migrations.AlterField(
            model_name='voyageslavesnumbers',
            name='percentage_child',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name=b'Percentage children on voyage (CHILRAT7)'),
        ),
        migrations.AlterField(
            model_name='voyageslavesnumbers',
            name='percentage_girl',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name=b'Percentage girl on voyage (GIRLRAT7)'),
        ),
        migrations.AlterField(
            model_name='voyageslavesnumbers',
            name='percentage_male',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name=b'Percentage male on voyage (MALRAT7)'),
        ),
        migrations.AlterField(
            model_name='voyageslavesnumbers',
            name='percentage_men',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name=b'Percentage men on voyage (MENRAT7)'),
        ),
        migrations.AlterField(
            model_name='voyageslavesnumbers',
            name='percentage_women',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name=b'Percentage women on voyage (WOMRAT7)'),
        ),
        migrations.AlterField(
            model_name='voyagesources',
            name='full_ref',
            field=models.CharField(blank=True,
                                   default='',
                                   max_length=2550,
                                   verbose_name='Full reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voyagesources',
            name='short_ref',
            field=models.CharField(blank=True,
                                   default='',
                                   max_length=255,
                                   unique=True,
                                   verbose_name='Short reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voyagesources',
            name='source_type',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='voyage.VoyageSourcesType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voyagesourcesconnection',
            name='source',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='source',
                to='voyage.VoyageSources'),
        ),
        migrations.AlterField(
            model_name='voyagesourcesconnection',
            name='text_ref',
            field=models.CharField(blank=True,
                                   default='',
                                   max_length=255,
                                   verbose_name='Text reference(citation)'),
            preserve_default=False,
        ),
    ]
