# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-11-16 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0014_auto_20200909_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['value'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
    ]
