# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0015_auto_20211116_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedvoyages',
            name='second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_from_other_voyages', to='voyage.Voyage'),
        ),
    ]
