# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0016_auto_20220602_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfricanInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoyageCargoConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True, verbose_name='The amount of cargo according to the unit')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.CargoType')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.CargoUnit')),
            ],
        ),
        migrations.AddField(
            model_name='voyage',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyagecargoconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.Voyage'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='african_info',
            field=models.ManyToManyField(blank=True, related_name='african_info', to='voyage.AfricanInfo'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='cargo',
            field=models.ManyToManyField(blank=True, through='voyage.VoyageCargoConnection', to='voyage.CargoType'),
        ),
    ]
