# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-18 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0017_auto_20220613_1816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voyagecargoconnection',
            unique_together=set([('voyage', 'cargo')]),
        ),
    ]
