# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-01-31 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0019_africaninfo_possibly_offensive'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageitinerary',
            name='int_fourth_place_region_slave_landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int_fourth_region_slave_landing', to='voyage.Region', verbose_name='Fourth intended region of slave landing (REGARR4)'),
        ),
        migrations.AddField(
            model_name='voyageitinerary',
            name='int_fourth_port_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int_fourth_port_dis', to='voyage.Place', verbose_name='Fourth intended port of disembarkation (ARRPORT4)'),
        ),
        migrations.AddField(
            model_name='voyageitinerary',
            name='int_third_place_region_slave_landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int_third_region_slave_landing', to='voyage.Region', verbose_name='Third intended region of slave landing (REGARR3)'),
        ),
        migrations.AddField(
            model_name='voyageitinerary',
            name='int_third_port_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int_third_port_dis', to='voyage.Place', verbose_name='Third intended port of disembarkation (ARRPORT3)'),
        ),
    ]
