// form data //
// flag
var flagData = [
	{id:0, text: gettext('Spain'), value:"1"},
	{id:1, text: gettext('Uruguay'), value:"1"},
	{id:2, text: gettext('Portugal'), value:"1"},
	{id:3, text: gettext('Brazil'), value:"1"},
	{id:4, text: gettext('Great Britain'), value:"1"},
	{id:5, text: gettext('Netherlands'), value:"1"},
	{id:6, text: gettext('U.S.A'), value:"1"},
	{id:7, text: gettext('France'), value:"1"},
	{id:8, text: gettext('Denmark'), value:"1"},
	{id:9, text: gettext('Hanse Towns, Brandenburg'), value:"1"},
	{id:10, text: gettext('Sweden'), value:"1"},
	{id:11, text: gettext('Norway'), value:"1"},
	{id:12, text: gettext('Argentina'), value:"1"},
	{id:13, text: gettext('Russia'), value:"1"},
	{id:14, text: gettext('Sardinia'), value:"1"},
	{id:15, text: gettext('Mexico'), value:"1"},
	{id:16, text: gettext('Genoa'), value:"1"},
	{id:17, text: gettext('Duchy of Courland'), value:"1"},
	{id:18, text: gettext('Prussia'), value:"1"},
	{id:19, text: gettext('Bremen'), value:"1"},
	{id:20, text: gettext('Other'), value:"1"}
]

// flag-imputed
var flagImputedData = [
	{id:0, text: gettext('Spain/Uruguay'), value:"1"},
	{id:1, text: gettext('Portugal/Brazil'), value:"1"},
	{id:2, text: gettext('Great Britain'), value:"1"},
	{id:3, text: gettext('Netherlands'), value:"1"},
	{id:4, text: gettext('U.S.A'), value:"1"},
	{id:5, text: gettext('France'), value:"1"},
	{id:6, text: gettext('U.S.A'), value:"1"},
	{id:7, text: gettext('Denmark/Baltic'), value:"1"}
]

// rig
var rigData = [
	{id:0, value:"1", text: gettext("Brig")},
	{id:1, value:"2", text: gettext("Schooner")},
	{id:2, value:"3", text: gettext("Curveta")},
	{id:3, value:"4", text: gettext("Ship")},
	{id:4, value:"5", text: gettext("Schooner-brig")},
	{id:5, value:"6", text: gettext("Smack")},
	{id:6, value:"7", text: gettext("Patacho")},
	{id:7, value:"8", text: gettext("Brigantine")},
	{id:8, value:"9", text: gettext("Barque")},
	{id:9, value:"10", text: gettext("Polacca schooner")},
	{id:10, value:"11", text: gettext("Pailebot")},
	{id:11, value:"12", text: gettext("Pilot boat")},
	{id:12, value:"13", text: gettext("Sumaca")},
	{id:13, value:"14", text: gettext("Yacht")},
	{id:14, value:"15", text: gettext("Felucca")},
	{id:15, value:"16", text: gettext("Galliot")},
	{id:16, value:"17", text: gettext("Cutter")},
	{id:17, value:"18", text: gettext("Pinnace")},
	{id:18, value:"19", text: gettext("Launch")},
	{id:19, value:"20", text: gettext("Barqua")},
	{id:20, value:"21", text: gettext("Navio mercante")},
	{id:21, value:"22", text: gettext("Charrua de guerra")},
	{id:22, value:"23", text: gettext("Chalupa")},
	{id:23, value:"24", text: gettext("Pollaca")},
	{id:24, value:"25", text: gettext("Galera")},
	{id:25, value:"26", text: gettext("Vessel")},
	{id:26, value:"27", text: gettext("Sloop")},
	{id:27, value:"28", text: gettext("Steamer")},
	{id:28, value:"29", text: gettext("Whaler")},
	{id:29, value:"30", text: gettext("Fregat")},
	{id:30, value:"31", text: gettext("Barque (Dutch)")},
	{id:31, value:"32", text: gettext("Fluit")},
	{id:32, value:"33", text: gettext("Brik")},
	{id:33, value:"34", text: gettext("Hoeker")},
	{id:34, value:"35", text: gettext("Snauw")},
	{id:35, value:"36", text: gettext("Yaght")},
	{id:36, value:"37", text: gettext("Pinas")},
	{id:37, value:"38", text: gettext("Galjoot")},
	{id:38, value:"39", text: gettext("Hekboot")},
	{id:39, value:"40", text: gettext("Bergantin")},
	{id:40, value:"41", text: gettext("Penque")},
	{id:41, value:"42", text: gettext("Não")},
	{id:42, value:"43", text: gettext("Corsario")},
	{id:43, value:"44", text: gettext("Charrua")},
	{id:44, value:"45", text: gettext("Fregata")},
	{id:45, value:"46", text: gettext("Charrauinha")},
	{id:46, value:"47", text: gettext("Balandra")},
	{id:47, value:"48", text: gettext("Paquete")},
	{id:48, value:"49", text: gettext("Hyate (iate)")},
	{id:49, value:"50", text: gettext("Berlin")},
	{id:50, value:"51", text: gettext("Goleta")},
	{id:51, value:"52", text: gettext("Lugger")},
	{id:52, value:"53", text: gettext("Ketch")},
	{id:53, value:"54", text: gettext("Billd")},
	{id:54, value:"55", text: gettext("Boat")},
	{id:55, value:"56", text: gettext("shallop (a) shalp")},
	{id:56, value:"57", text: gettext("Pink")},
	{id:57, value:"58", text: gettext("Hay")},
	{id:58, value:"59", text: gettext("Dogger")},
	{id:59, value:"60", text: gettext("Buque")},
	{id:60, value:"61", text: gettext("Laud")},
	{id:61, value:"62", text: gettext("Brigue-escuna")},
	{id:62, value:"63", text: gettext("Fragatihna")},
	{id:63, value:"64", text: gettext("Nau caravela")},
	{id:64, value:"65", text: gettext("Lancha")},
	{id:65, value:"66", text: gettext("Talaveira")},
	{id:66, value:"67", text: gettext("Batelão")},
	{id:67, value:"70", text: gettext("Caravela")},
	{id:68, value:"71", text: gettext("Galeão")},
	{id:69, value:"72", text: gettext("Nau-Caravela")},
	{id:70, value:"75", text: gettext("Faluxo")},
	{id:71, value:"76", text: gettext("xixorro")},
	{id:72, value:"77", text: gettext("Vasca")},
	{id:73, value:"80", text: gettext("Pangaio")},
	{id:74, value:"81", text: gettext("Palla")},
	{id:75, value:"82", text: gettext("Barca")},
	{id:76, value:"83", text: gettext("Escaller")},
	{id:77, value:"84", text: gettext("Filibote")},
	{id:78, value:"85", text: gettext("Urca")},
	{id:79, value:"86", text: gettext("Pinnace")},
	{id:80, value:"87", text: gettext("Columpo")},
	{id:81, value:"88", text: gettext("Periagua (a) petty augre")},
	{id:82, value:"89", text: gettext("Broad sterne")},
	{id:83, value:"90", text: gettext("Guardacosta")},
	{id:84, value:"99", text: gettext("Other (specify in note)")}
]




var outcome1 = [
{id:0, text: gettext("Voyage completed as intended"), value: 0},
{id:1, text: gettext("Shipwrecked or destroyed, before slaves embarked"), value: 1},
{id:2, text: gettext("Shipwrecked or destroyed, after embarkation of slaves or during slaving"), value: 2},
{id:3, text: gettext("Shipwrecked or destroyed, after disembarkation"), value: 3},
{id:4, text: gettext("Shipwrecked or destroyed - unspecified"), value: 4},
{id:5, text: gettext("Captured by pirates or privateers - before slaves embarked"), value: 5},
{id:6, text: gettext("Captured by pirates or privateers - after embarkation of slaves"), value: 6},
{id:7, text: gettext("Captured by pirates or privateers - after disembarkation"), value: 7},
{id:8, text: gettext("Captured by pirates or privateers - unspecified"), value: 8},
{id:9, text: gettext("Captured by British - before slaves embarked"), value: 9},
{id:10, text: gettext("Captured by British - after embarkation of slaves"), value: 10},
{id:11, text: gettext("Captured by British - after disembarkation"), value: 11},
{id:12, text: gettext("Captured by British - unspecified"), value: 12},
{id:13, text: gettext("Captured by Spanish - before slaves embarked"), value: 13},
{id:14, text: gettext("Captured by Spanish - after embarkation of slaves"), value: 14},
{id:15, text: gettext("Captured by Spanish - after disembarkation"), value: 15},
{id:16, text: gettext("Captured by Spanish - unspecified"), value: 16},
{id:17, text: gettext("Captured by Dutch - before slaves embarked"), value: 17},
{id:18, text: gettext("Captured by Dutch - after embarkation of slaves"), value: 18},
{id:19, text: gettext("Captured by Dutch - after disembarkation"), value: 19},
{id:20, text: gettext("Captured by Dutch - unspecified"), value: 20},
{id:21, text: gettext("Captured by Portuguese - before slaves embarked"), value: 21},
{id:22, text: gettext("Captured by Portuguese - after embarkation of slaves"), value: 22},
{id:23, text: gettext("Captured by Portuguese - Americas after disembarkation"), value: 23},
{id:24, text: gettext("Captured by Portuguese - unspecified"), value: 24},
{id:25, text: gettext("Captured - unspecified"), value: 25},
{id:26, text: gettext("Condemned - before slaves embarked"), value: 26},
{id:27, text: gettext("Condemned - after embarkation of slaves"), value: 27},
{id:28, text: gettext("Condemned - Americas after disembarkation"), value: 28},
{id:29, text: gettext("Condemned - unspecified"), value: 29},
{id:30, text: gettext("Captured by the Barbary Powers before embarking slaves"), value: 30},
{id:31, text: gettext("Destroyed - unspecified"), value: 31},
{id:32, text: gettext("Sold"), value: 32},
{id:33, text: gettext("Left coast with trading cargo intact"), value: 33},
{id:34, text: gettext("Taken by Africans"), value: 34},
{id:35, text: gettext("Captured by Cie du Senegal"), value: 35},
{id:36, text: gettext("Abandoned and/or sold off Africa"), value: 36},
{id:37, text: gettext("Captured unspecified before slaves embarked"), value: 37},
{id:38, text: gettext("Captured unspecified after embarkation of slaves"), value: 38},
{id:39, text: gettext("Captured unspecified after slaves disembarked"), value: 39},
{id:40, text: gettext("Captured by pirates - slaves sold in Americas from another ship"), value: 40},
{id:41, text: gettext("Sold slaves in Americas - subsequent fate unknown"), value: 41},
{id:42, text: gettext("Captured by the French - before slaves embarked"), value: 42},
{id:43, text: gettext("Captured by the French - after embarkation of slaves"), value: 43},
{id:44, text: gettext("Captured by the French - after slaves disembarked"), value: 44},
{id:45, text: gettext("Captured by the French - unspecified"), value: 45},
{id:46, text: gettext("Condemned in the Americas by British after slaves disembarked"), value: 46},
{id:47, text: gettext("Pressed into government service"), value: 47},
{id:48, text: gettext("Captured by slaves: ship did not reach the Americas"), value: 48},
{id:49, text: gettext("Captured by crew: fate unknown"), value: 49},
{id:50, text: gettext("Condemned in the Americas by British before slaves disembarked"), value: 50},
{id:51, text: gettext("Bought at least one slave in Africa - subsequent fate unknown"), value: 51},
{id:52, text: gettext("Destroyed, lost or sold as result of slave rebellion"), value: 52},
{id:53, text: gettext("Taken, retaken and salvaged before reaching African trade site"), value: 53},
{id:54, text: gettext("Sold in the Americas after disembarking slaves"), value: 54},
{id:55, text: gettext("Cut off by Africans from shore, ship did not reach the Americas"), value: 55},
{id:56, text: gettext("Sold in the Americas - not known whether ship brought slaves"), value: 56},
{id:57, text: gettext("Captured before disembarking slaves; vessel recaptured or released subsequently"), value: 57},
{id:58, text: gettext("Driven off the African Coast with slaves on board"), value: 58},
{id:59, text: gettext("Captured by slaves, unknown outcome"), value: 59},
{id:60, text: gettext("Captured by crew, did not land slaves in the Americas"), value: 60},
{id:61, text: gettext("Lost before reaching Americas: slaves reached port in other ships"), value: 61},
{id:62, text: gettext("Some slaves removed by pirates/privateers"), value: 62},
{id:63, text: gettext("Arrived in Africa, subsequent fate unknown"), value: 63},
{id:64, text: gettext("Captured and recaptured after disembarking slaves"), value: 64},
{id:65, text: gettext("Crew mutiny; slaves landed in the Americas"), value: 65},
{id:66, text: gettext("Cut off by Africans from shore. Recaptured and landed slaves in Americas"), value: 66},
{id:67, text: gettext("Captured by slaves, recaptured and landed slaves in the Americas"), value: 67},
{id:68, text: gettext("Captured by slaves, recaptured and landed slaves in the Americas, lost"), value: 68},
{id:69, text: gettext("to be completed after Curto consulted on Arquivos Angola, II, vol 25, pp.189-91."), value: 69},
{id:70, text: gettext("ditto Arquivos Angola, II, vol 25, pp. 432-33."), value: 70},
{id:71, text: gettext("Completed voyage after slaves removed for salvage"), value: 71},
{id:72, text: gettext("Ship returned direct to home port after selling slaves to another vessel"), value: 72},
{id:73, text: gettext("Taken by slaves, vessel recaptured, unknown outcome"), value: 73},
{id:74, text: gettext("Sold prematurely in Europe after disembarking slaves in the Americas"), value: 74},
{id:75, text: gettext("Captured by the crew, slaves sold in Africa"), value: 75},
{id:76, text: gettext("Captured by the crew, no slaves taken, crew sold gold in Europe"), value: 76},
{id:77, text: gettext("Condemned in Africa with slaves, slaves transshipped/sold"), value: 77},
{id:78, text: gettext("Returned direct to Africa after bringing slaves to the Americas"), value: 78},
{id:79, text: gettext("Returned to Europe or Americas without obtaining slaves"), value: 79},
{id:80, text: gettext("Laid up (disarmed) or broken up in Africa"), value: 80},
{id:81, text: gettext("Laid up (disarmed) or broken up in the Americas"), value: 81},
{id:82, text: gettext("Either shipwrecked or captured by pirates before slaves taken on board"), value: 82},
{id:83, text: gettext("Abandoned or condemned for unseaworthiness in the Americas"), value: 83},
{id:84, text: gettext("Ship and slaves sold in Africa"), value: 84},
{id:85, text: gettext("Taken by slaves, recaptured, then ship lost"), value: 85},
{id:86, text: gettext("Vice-Admiralty Court, St.Helena, condemned"), value: 86},
{id:87, text: gettext("Vice-Admiralty Court, St. Helena, restored"), value: 87},
{id:88, text: gettext("Vice-Admiralty Court, British Guiana, condemned"), value: 88},
{id:89, text: gettext("Vice-Admiralty Court, British Guiana, restored"), value: 89},
{id:90, text: gettext("Vice-Admiralty Court, Cape of Good Hope, condemned"), value: 90},
{id:91, text: gettext("Vice-Admiralty Court, Cape of Good Hope, restored"), value: 91},
{id:92, text: gettext("Vice-Admiralty Court, Jamaica, condemned"), value: 92},
{id:93, text: gettext("Vice-Admiralty Court, Jamaica, restored"), value: 93},
{id:94, text: gettext("Vice-Admiralty Court, Sierra Leone, condemned ,"), value: 94},
{id:95, text: gettext("Vice-Admiralty Court, Sierra Leone, restored"), value: 95},
{id:96, text: gettext("Vice-Admiralty Court, Barbados, condemned"), value: 96},
{id:97, text: gettext("Vice-Admiralty Court, Barbados, restored"), value: 97},
{id:98, text: gettext("Vice-Admiralty Court, Mauritius, condemned"), value: 98},
{id:99, text: gettext("Vice-Admiralty Court, Mauritius, restored"), value: 99},
{id:100, text: gettext("High Court of Admiralty, condemned"), value: 100},
{id:101, text: gettext("High Court of Admiralty, restored"), value: 101},
{id:102, text: gettext("Court of Mixed Commission, Sierra Leone, condemned"), value: 102},
{id:103, text: gettext("Court of Mixed Commission, Sierra Leone, restored"), value: 103},
{id:104, text: gettext("Court of Mixed Commission, Havana, condemned"), value: 104},
{id:105, text: gettext("Court of Mixed Commission, Havana, restored"), value: 105},
{id:106, text: gettext("Court of Mixed Commission, Rio de Janeiro, condemned"), value: 106},
{id:107, text: gettext("Court of Mixed Commission, Rio de Janeiro, restored"), value: 107},
{id:108, text: gettext("Court of Mixed Commission, Luanda, condemned"), value: 108},
{id:109, text: gettext("Court of Mixed Commission, Luanda, restored"), value: 109},
{id:110, text: gettext("Court of Mixed Commission, Cape of Good Hope, condemned"), value: 110},
{id:111, text: gettext("Court of Mixed Commission, Cape of Good Hope, restored"), value: 111},
{id:112, text: gettext("Lagos, Vice-Admiralty Court, condemned"), value: 112},
{id:113, text: gettext("Vice-Admiralty Court, Antigua, condemned"), value: 113},
{id:114, text: gettext("Vice-Admiralty Court, Tortola, condemned"), value: 114},
{id:115, text: gettext("Vice-Admiralty Court, Tortola, restored"), value: 115},
{id:116, text: gettext("Vice-Admiralty Court, Halifax, Condemned"), value: 116},
{id:117, text: gettext("Vice-Admiralty Court, unspecified, condemned"), value: 117},
{id:118, text: gettext("Vice-Admiralty Court, unspecified, restored"), value: 118},
{id:119, text: gettext("Given up to the United States government"), value: 119},
{id:120, text: gettext("Arrested by Brazil or given up to the Brazilian government"), value: 120},
{id:121, text: gettext("Vice Admiralty Court, Dominica, condemned"), value: 121},
{id:122, text: gettext("Vice-Admiralty Court, Bahamas, condemned"), value: 122},
{id:123, text: gettext("Vice-Admiralty Court, Bahamas, restored"), value: 123},
{id:124, text: gettext("Captured and released without court proceedings"), value: 124},
{id:125, text: gettext("Driven or run on shore in the Americas: no court proceedings"), value: 125},
{id:126, text: gettext("Given up to the Mexican Government, Vera Cruz"), value: 126},
{id:127, text: gettext("Taken to Genoa and given up to Sardinian authorities"), value: 127},
{id:128, text: gettext("Abandoned in Europe after completing voyage"), value: 128},
{id:129, text: gettext("Captured by Argentinian privateers after embarkation of slaves"), value: 129},
{id:130, text: gettext("Captured by United States before slaves embarked"), value: 130},
{id:131, text: gettext("Captured by United States with slaves"), value: 131},
{id:132, text: gettext("Captured by United States after slaves disembarked"), value: 132},
{id:133, text: gettext("Captured by United States, slave presence unspecified"), value: 133},
{id:134, text: gettext("French proceedings initiated in Africa, acquittal"), value: 134},
{id:135, text: gettext("French proceedings initiated in Africa, condemned"), value: 135},
{id:136, text: gettext("French proceedings initiated in Africa, unknown outcome"), value: 136},
{id:137, text: gettext("French proceedings, initiated in unknown location, acquittal"), value: 137},
{id:138, text: gettext("French proceedings, initiated in unknown location, condemned"), value: 138},
{id:139, text: gettext("French proceedings, initiated in unknown location, unknown outcome"), value: 139},
{id:140, text: gettext("French proceedings initiated in Guadaloupe, acquittal"), value: 140},
{id:141, text: gettext("French proceedings initiated in Guadaloupe, condemned"), value: 141},
{id:142, text: gettext("French proceedings initiated in Guadaloupe, unknown outcome"), value: 142},
{id:143, text: gettext("French proceedings initiated in Martinique, acquittal"), value: 143},
{id:144, text: gettext("French proceedings initiated in Martinique, condemned"), value: 144},
{id:145, text: gettext("French proceedings initiated in Martinique, unknown outcome"), value: 145},
{id:146, text: gettext("French proceedings initiated in Cayenne, acquittal"), value: 146},
{id:147, text: gettext("French proceedings initiated in Cayenne, condemned"), value: 147},
{id:148, text: gettext("French proceedings initiated in Cayenne, unknown outcome"), value: 148},
{id:149, text: gettext("French proceedings initiated in France, acquittal"), value: 149},
{id:150, text: gettext("French proceedings initiated in France, condemned"), value: 150},
{id:151, text: gettext("French proceedings initiated in France, unknown outcome"), value: 151},
{id:152, text: gettext("Detained and condemned in the United States after slaves disembarked"), value: 152},
{id:153, text: gettext("Captured by Dutch, slaves turned loose in Africa"), value: 153},
{id:154, text: gettext("Captured by Dutch, slaves turned loose in Brazil"), value: 154},
{id:155, text: gettext("Temporarily detained by the Dutch: Voyage allowed to continue with slaves"), value: 155},
{id:156, text: gettext("Slaves are removed by the Dutch and vessel allowed to continue, subsequent fate unknown"), value: 156},
{id:157, text: gettext("Captured by Portuguese and Dutch"), value: 157},
{id:158, text: gettext("Captured by Algerian pirates"), value: 158},
{id:159, text: gettext("Captured by Turks"), value: 159},
{id:160, text: gettext("Captured by British, released"), value: 160},
{id:161, text: gettext("Looted by Dutch at Elmina"), value: 161},
{id:162, text: gettext("Captured by first by the British and then by the Dutch after slaves embarked"), value: 162},
{id:163, text: gettext("Vessel driven back into Portdep by British and voyage aborted"), value: 163},
{id:164, text: gettext("Arrived in Brazil and refused permission to disembark"), value: 164},
{id:165, text: gettext("Ship and cargo captured by Africans and ship released"), value: 165},
{id:166, text: gettext("Ship captured by Haitian navy and slaves released in Haiti"), value: 166},
{id:167, text: gettext("Condemned at Goree by the British"), value: 167},
{id:168, text: gettext("Captured by the British, retaken by original crew, completed voyage"), value: 168},
{id:169, text: gettext("Captured by pirates after slaves embarked, ship and slaves burned."), value: 169},
{id:170, text: gettext("Captured by English, slaves turned loose on Spanish Main"), value: 170},
{id:171, text: gettext("Sold slaves in Africa"), value: 171},
{id:172, text: gettext("Sold slaves in Europe - subsequent fate unknown"), value: 172},
{id:173, text: gettext("Left home port, no further record"), value: 173},
{id:174, text: gettext("captured by pirates and burned"), value: 174},
{id:175, text: gettext("looted by pirates, voyage continued"), value: 175},
{id:176, text: gettext("captured by Venezuelans before disembarkation of slaves"), value: 176},
{id:177, text: gettext("Captured by the Swedes"), value: 177},
{id:178, text: gettext("Captured by the Dominican Republic"), value: 178},
{id:179, text: gettext("Departed an American port with slaves, subsequent fate unknown"), value: 179},
{id:180, text: gettext("Returned to Port of embarkation without having sold slaves"), value: 180},
{id:181, text: gettext("Privateer captured slaves at sea and delivered for sale in America"), value: 181},
{id:182, text: gettext("Prisoners of war stole slaves during escape and carried to port of sale"), value: 182},
{id:183, text: gettext("Other (specify in note)"), value: 183}

];

var outcome2 = [
	{id:0, text: gettext("Slaves disembarked in Americas"), value: 0},
	{id:1, text: gettext("No slaves embarked"), value: 1},
	{id:2, text: gettext("Slaves disembarked in Old World"), value: 2},
	{id:3, text: gettext("Slaves perished with ship"), value: 3},
	{id:4, text: gettext("Slaves embarked, transhipped or no further record"), value: 4},
	{id:5, text: gettext("No information on slaves"), value: 5},
	{id:6, text: gettext("Slaves embarked but not disembarked in Europe or America"), value: 6}
];

var outcome3 = [
	{id:0, text: gettext("Natural hazard"), value: 0},
	{id:1, text: gettext("pirate/privateer action"), value: 1},
	{id:2, text: gettext("British"), value: 2},
	{id:3, text: gettext("Spanish"), value: 3},
	{id:4, text: gettext("Dutch"), value: 4},
	{id:5, text: gettext("Portuguese"), value: 5},
	{id:6, text: gettext("French"), value: 6},
	{id:7, text: gettext("US"), value: 7},
	{id:8, text: gettext("African"), value: 8},
	{id:9, text: gettext("Crew action"), value: 9},
	{id:10, text: gettext("Brazil"), value: 10},
	{id:11, text: gettext("Captor unspecified"), value: 11},
	{id:12, text: gettext("Not captured"), value: 12},
	{id:13, text: gettext("Unknown"), value: 13},
	{id:14, text: gettext("Haitians"), value: 14},
	{id:15, text: gettext("Venezuela"), value: 15},
	{id:16, text: gettext("Sweden"), value: 16}
];


var outcome4 = [
	{id:0, text: gettext("Delivered slaves for original owners"), value: 0},
	{id:1, text: gettext("Original goal thwarted (natural hazard)"), value: 1},
	{id:2, text: gettext("Original goal thwarted (human agency)"), value: 2},
	{id:3, text: gettext("Unknown outcome"), value: 3}
]

var outcome5 = [
	{id:0, text: gettext("Slave insurrection"), value: 0},
	{id:1, text: gettext("Vessel attacked from shore"), value: 1},
	{id:2, text: gettext("Vessel's boats attacked from shore"), value: 2},
	{id:3, text: gettext("Cut-off (meaning unclear)"), value: 3},
	{id:4, text: gettext("Three or more slaves jumping overboard, missing, or escaped"), value: 4},
	{id:5, text: gettext("Insurrection planned, but thwarted"), value: 5},
	{id:6, text: gettext("Other (specify in note)"), value: 6}
]
