/* Manage links  for the navigation left menu in the Methodology section of the Voyage section */
var methodology_toc = {
	"01": "Introduction", 
	"02": "Coverage of the Slave Trade", 
	"03": "Nature of Sources", 
	"04": "Cases and Variables", 
	"05": "Data Variables", 
	"22": "Age Categories", 
	"06": "Dates", 
	"07": "Names", 
	"08": "Imputed Variables", 
	"09": "Geographic Data", 
	"10": "Imputed Voyage Dates", 
	"11": "Classification as a Trans-Atlantic Slaving Voyage", 
	"12": "Voyage Outcomes", 
	"13": "Inferring Places of Trade", 
	"14": "Imputing Numbers of Slaves", 
	"15": "Regions of Embarkation and Disembarkation", 
	"16": "Age and Gender Ratios", 
	"17": "National Carriers", 
	"18": "Tonnage", 
	"19": "Resistance and Price of Slaves", 
	"20": "Appendix", 
	"21": "Notes", 
}